# Generated by Django 2.2.4 on 2019-08-16 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190816_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 16, 8, 36, 18, 641415, tzinfo=utc)),
        ),
    ]
