# Generated by Django 2.2.4 on 2019-08-17 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190817_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 17, 6, 50, 34, 202333, tzinfo=utc)),
        ),
    ]
