# Generated by Django 2.2.4 on 2019-08-17 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190817_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 17, 7, 56, 28, 185671, tzinfo=utc)),
        ),
    ]
