# Generated by Django 2.2.4 on 2019-08-18 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190818_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 6, 33, 6, 681281, tzinfo=utc)),
        ),
    ]
