# Generated by Django 2.2.4 on 2019-08-18 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190818_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 12, 7, 38, 262415)),
        ),
    ]
