# Generated by Django 2.2.4 on 2019-08-22 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190822_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 10, 57, 39, 565790)),
        ),
    ]
